logging:
  level:
    root: info
    com.aims.assembly: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
  file:
    path: ${LOG_PATH:logs/local}

management:
  health:
    redis:
      enabled: true
    kafka:
      enabled: false